export enum Microservice {
    AUTH_SERVICE = 'AUTH_SERVICE',
    MEDIA_SERVICE = 'MEDIA_SERVICE',
    ORDER_SERVICE = 'ORDER_SERVICE',
    PAYMENT_SERVICE = 'PAYMENT_SERVICE',
    PRODUCT_SERVICE = 'PRODUCT_SERVICE',
}